### ISSUE TITLE
引入后使用报错

### ISSUE THREAD

**Issue by h7ml** [tnfe/csijs#1]
### 报错信息
`` TypeError: Illegal invocation``
![image](https://user-images.githubusercontent.com/55233292/144840584-b4827d6c-05c2-4f05-85bc-24a49e87a85c.png)

### 使用方法
``npm``
![image](https://user-images.githubusercontent.com/55233292/144840456-0a944ed5-859e-401a-94e7-6beaff9e4797.png)

### 使用版本
``    "csijs": "^1.0.9",``

**Comment by aliaszz** [comment]
你好，感谢使用 csjis~
可以提供一下发生报错请求时的 Ajax 相关代码嘛，目前提供的信息还不够定位问题。

**Comment by h7ml** [comment]
放开[repo](https://github.com/dgiot/dgiot-dashboard/blob/master/src/dgiot/plugins/csi.js#L1)12到22行的注释即可
