### ISSUE TITLE
可以给一个vue实践的demo吗

### ISSUE THREAD

**Issue by shishezhang** [tnfe/csijs#3]
在App.vue中created钩子上执行并没有起作用
![image](https://user-images.githubusercontent.com/50197267/152901963-ea27501f-c5b1-4a26-b53a-7dd99adcc115.png)
在控制台也输出了初始化成功
![image](https://user-images.githubusercontent.com/50197267/152902187-ff4ed8d5-b5cb-47bb-99e2-5131a220af94.png)

**Comment by aliaszz** [comment]
你好，可以查看下未上报的部分是否有独立的异常捕获逻辑。如果有的话，推荐使用手动上报`csi.report();`。

**Comment by shishezhang** [comment]
你好，已经可以使用了，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tnfe/csijs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tnfe/csijs] 可以给一个vue实践的demo吗 (Issue #3)





 
你好，可以查看下未上报的部分是否有独立的异常捕获逻辑。如果有的话，推荐使用手动上报csi.report();。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
