### ISSUE TITLE
【bug】promise 的 error 没有捕获

### ISSUE THREAD

**Issue by ysneo** [tnfe/csijs#4]
![image](https://user-images.githubusercontent.com/17615113/152942602-828b2a94-9b8b-4176-a0e0-8bd049a07404.png)

**Comment by aliaszz** [comment]
并未对`unhandledrejection `事件进行处理，此处建议捕获后手动上报。
可参考 [Promise文档](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#common_mistakes)
